/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IdAmbulanceWlList {
    }
}
declare global {
    interface HTMLIdAmbulanceWlListElement extends Components.IdAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLIdAmbulanceWlListElement: {
        prototype: HTMLIdAmbulanceWlListElement;
        new (): HTMLIdAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "id-ambulance-wl-list": HTMLIdAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface IdAmbulanceWlList {
    }
    interface IntrinsicElements {
        "id-ambulance-wl-list": IdAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "id-ambulance-wl-list": LocalJSX.IdAmbulanceWlList & JSXBase.HTMLAttributes<HTMLIdAmbulanceWlListElement>;
        }
    }
}
